replicaCount: 2

image:
  repository: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/fulfillment
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always

osb: {}

env:
  natsHost: "nats"
  natsPort: 4222
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments

service:
  port: 80
