apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fulfillment.fullname" . }}
  labels:
{{ include "fulfillment.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "fulfillment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      run: {{ include "fulfillment.name" . }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "fulfillment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        run: {{ include "fulfillment.name" . }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /prometheus
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}-{{ .Values.image.suffix }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: NATS_HOST
              value: "{{ .Release.Name }}-{{ .Values.env.natsHost }}"
            - name: NATS_PORT
              value: "{{ .Values.env.natsPort }}"
            - name: ORDERS_NEW
              value: "{{ .Values.env.newOrdersSubject }}"
            - name: ORDERS_SHIPPED
              value: "{{ .Values.env.shippedOrdersSubject }}"
          {{- include "fulfillment.oapm.connection" . | nindent 12 }}
          {{- include "fulfillment.oims.config" . | nindent 12 }}
