kafka:
  bootstrap:
    servers: streaming.${REGION}.oci.oraclecloud.com:9092
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config: ${KAFKA_SASL_JAAS_CONFIG}
tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
    http:
      url: ${OCI_TRACING_UPLOAD_URL}
      path: /20200101/observations/public-span?dataFormat=zipkin&dataFormatVersion=2&dataKey=${OCI_TRACING_PUBLIC_KEY}
    supportsJoin: false