micronaut:
  application:
    name: events
  server:
    thread-selection: io
  executors:
    io:
      n-threads: 75
      type: fixed
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

kafka:
  bootstrap:
    servers: localhost:9092

