micronaut:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: ${AWS_METRICS_NAMESPACE:micronaut_mushop}

datasources:
  default:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/mysql
