version: "3"

services:
#  # Edge router application entrypoint
  edge-router:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/edge-router:1.1.0
    hostname: edge-router
    restart: always
    ports:
      - "81:8080"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - reschedule=on-node-failure

  # Storefront application middleware
  api:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/api-native:1.0.0-SNAPSHOT
    hostname: api
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    ports:
      - "8080:80"
    environment:
      - MICRONAUT_HTTP_SERVICES_MUSHOP-CATALOGUE_URL=http://catalogue:8080
      - MICRONAUT_HTTP_SERVICES_MUSHOP-CARTS_URL=http://carts:8080
      - MICRONAUT_HTTP_SERVICES_MUSHOP-ORDERS_URL=http://orders:8082
      - MICRONAUT_HTTP_SERVICES_MUSHOP-USER_URL=http://user:8080
#      - MICRONAUT_HTTP_SERVICES_MUSHOP_NEWSLETTER_URL=
      - REDIS_URI=redis://session-db:6379

  # Static media assets
  assets:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/assets:1.0.0
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - reschedule=on-node-failure
      - PORT=3000
      - BUCKET_PAR
      - REGION

  # Redis session DB
  session-db:
    image: redis:alpine
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure

  # Storefront frontend
  storefront:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/storefront:2.1.2
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    ports:
      - "80:8080"
    environment:
      - reschedule=on-node-failure

  # OCI Catalog service
  catalogue:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/catalogue-native:1.0.0-SNAPSHOT
    restart: always
    depends_on:
      - oracledbcatalogue
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - DATASOURCES_DEFAULT_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - DATASOURCES_DEFAULT_URL=jdbc:oracle:thin:system/oracle@oracledbcatalogue:1521:xe
      - DATASOURCES_DEFAULT_USERNAME=system
      - DATASOURCES_DEFAULT_PASSWORD=oracle
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  # OCI Carts service
  carts:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/carts-openjdk:1.0.3-SNAPSHOT
    restart: always
    depends_on:
      - oracledbcarts
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - DATASOURCES_DEFAULT_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - DATASOURCES_DEFAULT_URL=jdbc:oracle:thin:system/oracle@oracledbcarts:1521:xe
      - DATASOURCES_DEFAULT_USERNAME=system
      - DATASOURCES_DEFAULT_PASSWORD=oracle
      - SODA_CREATE_USERNAME=true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  # OCI Orders service
  orders:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/orders-native:1.0.0-SNAPSHOT
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      - oracledborders
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
      - ORDERS_NEW=mushop-orders
      - ORDERS_SHIPPED=mushop-shipments
      - DATASOURCES_DEFAULT_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - DATASOURCES_DEFAULT_URL=jdbc:oracle:thin:system/oracle@oracledborders:1521:xe
      - DATASOURCES_DEFAULT_USERNAME=system
      - DATASOURCES_DEFAULT_PASSWORD=oracle
      - MICRONAUT_HTTP_SERVICES_USERS_URL=http://user:8080
      - MICRONAUT_HTTP_SERVICES_CARTS_URL=http://carts:8080
      - MICRONAUT_HTTP_SERVICES_PAYMENT_URL=http://payment:8080
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  # User service
  user:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/user-native:1.0.0-SNAPSHOT
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    depends_on:
      - oracledbuser
    environment:
      - DATASOURCES_DEFAULT_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - DATASOURCES_DEFAULT_URL=jdbc:oracle:thin:system/oracle@oracledbuser:1521:xe
      - DATASOURCES_DEFAULT_USERNAME=system
      - DATASOURCES_DEFAULT_PASSWORD=oracle
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  # Payment service
  payment:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/payment-native:1.0.0-SNAPSHOT
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - PAYMENT_DECLINE_AMOUNT=500
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  # Fulfillment service
  fulfillment:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/fulfillment-native:1.0.0-SNAPSHOT
    restart: always
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      - nats
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
      - ORDERS_NEW=mushop-orders
      - ORDERS_SHIPPED=mushop-shipments
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  nats:
    image: nats:2.2
    hostname: nats
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true

  oracledbcarts:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/oracle-database:18.4.0-xe
    restart: always

  oracledbuser:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/oracle-database:18.4.0-xe
    restart: always

  oracledbcatalogue:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/oracle-database:18.4.0-xe
    restart: always

  oracledborders:
    image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/oracle-database:18.4.0-xe
    restart: always

# system : oracle


