micronaut:
  application:
    name: user
  server:
    thread-selection: io
  executors:
    io:
      n-threads: 75
      type: fixed
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
      cloudwatch:
        enabled: false
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  prometheus:
    sensitive: false
    details-visible: ANONYMOUS
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

datasources:
  default:
    dialect: oracle
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
flyway:
  datasources:
    default:
      locations: classpath:db/migration
      baseline-version: 0
      baseline-on-migrate: true
