apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "events.fullname" . }}
  labels:
{{ include "events.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "events.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "events.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}-{{ .Values.global.imageSuffix | default .Values.image.suffix }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_HEALTH_ENABLED
              value: "false"
            {{- include "events.env.stream" . | nindent 12 }}
            {{- include "events.oapm.connection" . | nindent 12 }}
            {{- include "events.oims.config" . | nindent 12 }}
          ports:
            - containerPort: 8080
          livenessProbe:
            periodSeconds: 10
            initialDelaySeconds: 10
            httpGet:
              path: /health/liveness
              port: 8080
          readinessProbe:
            periodSeconds: 10
            initialDelaySeconds: 10
            httpGet:
              path: /health/readiness
              port: 8080
