global:
  ociAuthSecret: oci-credentials        # OCI authentication credentials secret name
  ossStreamSecret: oss-connection       # Previously created streaming secret name
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created separately
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created separately
  oadbConnectionSecret: oadb-connection # Name of connection secret created separately
  oosBucketSecret: oos-bucket           # Object storage bucket secret name (optional)

ingress:
  hosts: # Configure ingress to support host-specific routing
    # - yourname.mushop.com 

api:
  env:
    trackingEnabled:          # Flag that enables sending of tracking events to events service. If event service is not deployed set to "false".
    mediaUrl:                 # URL for catalog image assets (https://objectstorage.[REGION].oraclecloud.com/n/[NAMESPACE]/b/[BUCKET_NAME]/o/)
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)

carts:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

catalogue:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

orders:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

user:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available
 
secrets:
  streams:
    streamId:             # Stream OCID
    messageEndpoint:      # Stream messages endpoint URL 