micronaut:
  application:
    name: api
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
      cloudwatch:
        enabled: false
    enabled: true
  security:
    authentication: session
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        enabled: false
  http:
    client:
      follow-redirects: false
  caches:
    discovery-client:
      enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**