{{- if not .Values.global.oapmConnectionSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oapm-connection
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  zipkin_enabled: {{ default "false" | b64enc }}
  zipkin_url: {{ default "-" | b64enc }}
  zipkin_path: {{ default "-" | b64enc }}
{{- end -}}