micronaut:
  application:
    name: carts
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
    # Optimization: cache collection metadata to avoid extra roundtrips
    # to the database when opening a collection
    soda:
      properties:
        sharedMetadataCache: true
#      create-soda-user: ${SODA_CREATE_USERNAME:true}
      create-collections:
        - ${carts.collection}

endpoints:
  prometheus:
    sensitive: false
    details-visible: ANONYMOUS
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
carts:
  collection: cart