micronaut:
  metrics:
    export:
      oraclecloud:
        enabled: true
        namespace: ${ORACLECLOUD_METRICS_NAMESPACE:micronaut_mushop}
        resourceGroup: ${ORACLECLOUD_METRICS_RESOURCEGROUP:carts}
        compartmentId: ${ORACLECLOUD_METRICS_COMPARTMENT_ID}

oci:
  config:
    instance-principal:
      enabled: true

datasources:
  default:
    ocid: ${ORACLECLOUD_ATP_OCID}
    walletPassword: ${ORACLECLOUD_ATP_WALLET_PASSWORD}
    username: ${ORACLECLOUD_ATP_USERNAME}
    password: ${ORACLECLOUD_ATP_PASSWORD}
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
    # Optimization: cache collection metadata to avoid extra roundtrips
    # to the database when opening a collection
    soda:
      properties:
        sharedMetadataCache: true
      create-soda-user: false
      create-collections:
        - ${carts.collection}
tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
    http:
      url: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_URL}
      path: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_PATH}
    supportsJoin: false
