# and edit them there. Note that it will be sync'ed to all the Micronaut repos
name: Java CI - Gradle
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA: '11'
    strategy:
      fail-fast: false
      matrix:
        project-path: [
            'api',
            'catalogue',
            'events',
            'fulfillment',
            'functions/newsletter-subscription',
            'orders',
            'payment',
            'user'
        ]
        allow-native-image-failure: [false]
        include:
          - project-path: events
            allow-native-image-failure: true
    steps:
      # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA }}
      - name: Build with Gradle
        working-directory: src/${{ matrix.project-path }}
        run: |
          ./gradlew check --no-daemon --parallel --continue
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
      - name: Build with Gradle - NativeImage
        working-directory: src/${{ matrix.project-path }}
        run: |
          ./gradlew testNativeImage --no-daemon --parallel --continue
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
      - name: Login to OCIR
        uses: docker/login-action@v1
        with:
          registry: iad.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}
      - name: Push docker image - GraalVM
#        if: success() && github.event_name == 'push'
        working-directory: src/${{ matrix.project-path }}
        run: ./gradlew dockerPush --no-daemon
      - name: Push docker image - OpenJdk
#        if: success() && github.event_name == 'push'
        working-directory: src/${{ matrix.project-path }}
        run: ./gradlew dockerPush -PjavaBaseImage=openjdk --no-daemon
      - name: Push docker image - GraalVM Native Image
#        if: success() && github.event_name == 'push'
        working-directory: src/${{ matrix.project-path }}
        run: ./gradlew dockerPushNative --no-daemon
        continue-on-error: ${{ matrix.allow-native-image-failure }}