# and edit them there. Note that it will be sync'ed to all the Micronaut repos
name: Java CI - Maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  JAVA: '11'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-path: [
            'carts'
        ]
    steps:
      # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA }}
      - name: Build with Maven
        working-directory: src/${{ matrix.project-path }}
        run: |
          ./mvnw test --no-transfer-progress
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
  push-docker-images:
#    if: success() && github.event_name == 'push'
    needs: build
    runs-on: self-hosted
    strategy:
      matrix:
        project-path: [
            'carts'
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA }}
      - name: Login to OCIR
        uses: docker/login-action@v1
        with:
          registry: iad.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}
          logout: false
      - name: Push docker image - GraalVM
        working-directory: src/${{ matrix.project-path }}
        run: ./mvnw deploy -Dpackaging=docker -Djib.from.image=ghcr.io/graalvm/graalvm-ce:java11-21.1.0 -Ddocker.image.suffix=graalvm --no-transfer-progress
      - name: Push docker image - OpenJdk
        working-directory: src/${{ matrix.project-path }}
        run: ./mvnw deploy -Dpackaging=docker --no-transfer-progress
      - name: Push docker image - GraalVM Native Image
        working-directory: src/${{ matrix.project-path }}
        run: ./mvnw deploy -Dpackaging=docker-native -Ddocker.image.suffix=native --no-transfer-progress -Pgraalvm
